import Head from "next/head";
import Categories from "@/components/module/Categories";
import SearchBar from "@/components/module/SearchBar";
import CarsPage from "@/components/templates/CarsPage";
import carsData from "@/data/carsData";
import AllButton from "@/components/module/AllButton";

function Index() {
  const cars = carsData.slice(0, 3);

  return (
    <>
      <Head>
        <title>CarSale project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SearchBar />
        <Categories />
        <AllButton />
        <CarsPage data={cars} />
      </div>
    </>
  );
}

export default Index;
